### ISSUE TITLE
what does the pending here signify?

### ISSUE THREAD

**Issue by vigneshsankariyer1234567890** [sheimoria/givehub-client#24]
<img width="1280" alt="Screenshot 2021-07-22 at 10 14 41 AM" src="https://user-images.githubusercontent.com/68676914/126581851-cbdd7ae6-f7c0-450b-bc0a-551af951a01a.png">

is this pending related to admin-approval for charities?

if so, should it be there?

**Comment by sheimoria** [comment]
Its a request friend button, forgot to remove if viewer is viewing his/her own user profile
